name: Deploy to Server B (Mail Branch)

on:
  push:
    branches:
      - mail

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server B
        run: |
          sshpass -p ${{ secrets.SERVER_B_PASSWORD }} scp -r path/to/files/ ${SERVER_B_USERNAME}@${SERVER_B_HOST}:path/to/destination
        env:
          SERVER_B_HOST: ${{ secrets.SERVER_B_HOST }}
          SERVER_B_USERNAME: ${{ secrets.SERVER_B_USERNAME }}
          SERVER_B_PASSWORD: ${{ secrets.SERVER_B_PASSWORD }}
