name: Deploy to Test Server

on:
  push:
    branches:
      - developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy to Test Server
        uses: appleboy/ssh-action@master
        with:
          host: 103.152.79.56
          username: root
          password: apt@test
          port: 22
          script: |
            cd /var/www/html/
            git push -u maintestprod main
            # Additional commands for deployment
